### ISSUE TITLE
Site is not Secure

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#378]
Not possible by conventional means:
<img width="763" alt="screen shot 2017-09-29 at 11 02 18" src="https://user-images.githubusercontent.com/5732209/31012102-7e6376de-a508-11e7-892b-d5d2cc27036d.png">

...but @finnhodgkin has suggested this is possible e.g. https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html *if* we decide we want to do this at some point

**Comment by finnhodgkin** [comment]
I think this is actually pretty crucial. The first result for 'dwyl' on google is https://www.dwyl.com which returns a privacy error.

**Comment by finnhodgkin** [comment]
@markwilliamfirth I can't fix this without access to the nameservers:

![selection_074](https://user-images.githubusercontent.com/22300773/31134948-860925f4-a85b-11e7-8e63-4f8c82db4163.png)

The other option is to move the site to AWS or some other static web host that does provide ssl with custom domains. Seems like more effort than it's worth considering the site is going to be moved to PETE at some point soon.

**Comment by markwilliamfirth** [comment]
It's because google still thinks the site is https, but it's not it's http, so it throws a warning

**Comment by markwilliamfirth** [comment]
Perhaps the temp solution for this is to re-index / re-crawl the site via Google? As opposed to changing dns again and going with the cloudflare (or another alternative hack)

Or we just make #389 and move back to heroku

**Comment by markwilliamfirth** [comment]
<img width="200" alt="screen shot 2017-10-04 at 17 16 57" src="https://user-images.githubusercontent.com/5732209/31186877-db2daed4-a927-11e7-950b-24eb6a9c1ea4.png">


@finnhodgkin this one looks like it's solved now?

**Comment by finnhodgkin** [comment]
Hmm I'm still getting not secure. 

I think it must be cloudflare taking time to move stuff over, or something to do with browser caching on my machine.

![selection_083](https://user-images.githubusercontent.com/22300773/31186987-495bff82-a928-11e7-8bfc-a2f4c1633bb6.png)

**Comment by finnhodgkin** [comment]
Got a padlock on my phone now. Guess it must be weird caching issues (weird because it still doesn't work in incognito).

**Comment by iteles** [comment]
That's worth googling for 15mins @finnhodgkin!

**Comment by finnhodgkin** [comment]
I think it was just Cloudflare/the DNS taking time to fully move everything over. https is now working on my laptop and phone, and invoice.dwyl/hits are not working when accessed through https. Without access to the DNS it's hard to know what the solution is for this. 

There are some guides on Cloudflare for adding subdomains, but I think it has to be done by hand and I don't know the DNS settings for invoice/hits:

https://support.cloudflare.com/hc/en-us/articles/200168756-How-do-I-add-a-subdomain-

**Comment by finnhodgkin** [comment]
@markwilliamfirth How are the subdomains handled by the DNS? Do they just have extra records?

**Comment by iteles** [comment]
I'm on a train so don't have access just now but from what I remember they are just additional records pointing to the relevant heroku apps

**Comment by finnhodgkin** [comment]
Oh actually I can possibly just add exception rules to Cloudflare without needing access to the DNS. Trying now. Hard to tell if things work because it takes a while to update.

**Comment by finnhodgkin** [comment]
The Cloudflare exception didn't seem to fix anything. I'm now trying to add a page rule to forward https://invoice.dwyl.com requests to http://invoice.dwyl.com (the http version still works and forwards to the https google form anyway so ssl isn't required).

**Comment by markwilliamfirth** [comment]
@finnhodgkin do you still need access to iwantmyname?

**Comment by finnhodgkin** [comment]
No, not anymore. I need to give everyone access to Cloudflare though because all the dwyl.com DNS stuff is on there.

**Comment by markwilliamfirth** [comment]
Site is now secure

Closing in favour of https://github.com/dwyl/dwyl-site/issues/429
